### ISSUE TITLE
Setting row number to 1 causes to crash when selecting item from calendar

### ISSUE THREAD

**Issue by ukmarn** [patchthecode/JTAppleCalendar#107]
First of all thanks for this awesome library.

I am using it to create some kind of weekly calendar. As I change rows to 1, it works fine when scrolling but as soon as I select an item from calendar, it crashes.

Code:

```
numberOfRows = 1
self.calendarView.reloadData()
// After reloading. Scroll to your selected date, and setup your calendar
self.calendarView.scrollToDate(NSDate(), triggerScrollToDateDelegate: false, animateScroll: false) {
}
```

The error log:

> *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.60.7/UICollectionView.m:4422
2016-08-10 13:11:46.320 CalApp[23298:3801720] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete item 9 from section 46 which only contains 7 items before the update'

Xcode marks error row as: JTAppleCalendarView, batchReloadIndexPaths's completition (line 724)

Is it wrong something I am doing or is it library thing? Thanks for help

**Comment by patchthecode** [comment]
its a bug.
looking into it.

**Comment by patchthecode** [comment]
Fixed on master branch.

**Comment by ukmarn** [comment]
Thanks a lot!

**Comment by ukmarn** [comment]
@patchthecode I tried again and bug still exists. I have user instructions you provided. Also when scrolling through days (when calendar has only one row), days get skipped - current month is showing fine, september skips when scrolling to next week from 11 to 29.

**Comment by patchthecode** [comment]
ok are you online? mind messaging me [here](https://gitter.im/patchthecode/JTAppleCalendar)?

**Comment by patchthecode** [comment]
crash bug still exists. looking into it.

**Comment by patchthecode** [comment]
Fixed on master branch.

**Comment by seanrice** [comment]
hey patch. i'm still seeing the issue above. traced it down to single row. oddly, this error doesn't occur in your sample which ... naturally has me guessing.
