### ISSUE TITLE
scrollToDate() does not account for UICollectionView sectionInset property

### ISSUE THREAD

**Issue by johnuphoff** [patchthecode/JTAppleCalendar#419]
First - thanks for all your hard work on this calendar!
I am using JTAppleCalendar 7.02.

Calling calendarView.scrollToDate(Date(), triggerScrollToDateDelegate: true, animateScroll: false)
I noticed that the collection view was stopping between April & May.  I played around with the 
extraAddedOffset and realized the issue was related to the Section Inset.

The offset amount I needed to move the view into the correct position was 160pt.  This is because the offset for each section increases by 40 so for 4 sections (jan through apr), the offset must be increased by 40 for each month (160).  I'm not sure if it was intentional or not but thought I should bring it up.

The solution for now is to either not use section inset or to multiply the Integer month by the total inset amount and set that as the extraAddedOffset.

<img width="394" alt="screenshot 2017-05-17 14 34 43" src="https://cloud.githubusercontent.com/assets/5290771/26177632/4bad252c-3b0f-11e7-8936-30a16f7023f2.png">

**Comment by johnuphoff** [comment]
see https://github.com/patchthecode/JTAppleCalendar/pull/420

**Comment by patchthecode** [comment]
OK. Let me know if i understand correctly.

1. You have a horizontal calendar
2. You have a horizontal section inset
3. When you call `scrollToDate` in this state, the calendar does not properly scroll to the date?

**Comment by johnuphoff** [comment]
That is correct - I also tested with a vertical scroll calendar with the same result.

**Comment by bernikowich-cedoni** [comment]
Same issue here. I can post pull request if you want.

**Comment by jokerham** [comment]
I have the same problem. These are the images of the problem.

Todays date = 2017/07/17. If I call scrollToDate Today, this is what it happens.
1. Start date = 2017/06/01
![screenshot 2017-07-18 5 40 49](https://user-images.githubusercontent.com/8528842/28310853-57f00b86-6be0-11e7-9c3c-b3c45b0f422d.png)
2. Start date = 2017/05/01
![screenshot 2017-07-18 pm 5 42 16](https://user-images.githubusercontent.com/8528842/28310911-88b92ffe-6be0-11e7-9de0-225655dd8128.png)
3. Start date = 2017/04/01
![screenshot 2017-07-18 pm 5 43 38](https://user-images.githubusercontent.com/8528842/28310963-b1647b70-6be0-11e7-8f6a-593c8fc621b2.png)

As you can see, further the start dates are from Today, the further the offset gets.
When I tried the start date as 1900/01/01 the collection view was showing somewhere in year 2040.
I think the "cellCache" height information is not updated properly. Has anyone found a solution to this problem?

**Comment by jokerham** [comment]
Just realized that if I call the method twice, it finds it place correctly.

**Comment by jokerham** [comment]
Just realized that it shows correctly if I call the function twice. Wonder why.

**Comment by patchthecode** [comment]
@jokerham i will investigate this today.

**Comment by duyklinsi** [comment]
Same issue. Hope you will fix it soon @patchthecode

**Comment by patchthecode** [comment]
I got caught up last week.
I'll take a look in 11 hrs today.

**Comment by DominicMDev** [comment]
Same issue, but I'm using vertical scroll. The date cells appear aligned to the left after the scroll, but pop back into place when manually scrolling. @patchthecode

**Comment by Custo** [comment]
Seems like the same problem comes up when using scrollToDate(date:). It does not consider the sectionInset, too.

I have a year-overview-view (displaying the 12 months). When I tap on one of the months I want to show the JTAppleCalender scrolled to the selected month.

Im using Swift 4.0 with JTAppleCalendar 7.1.3

**Comment by patchthecode** [comment]
Yes.. this issue is opened, but i never got around to looking at it.
My time is to caught up.
Let me take a look after work today ok.

**Comment by juliensagot** [comment]
Hi, this issue seems to be still here: 
https://www.dropbox.com/s/1wyab52q7vk6zck/JTAppleCalendar_insetsIssue.mp4?dl=0

Could you please fix? This is really important for me to have insets 🙂

**Comment by patchthecode** [comment]
Hey guys, i have finally gotten around to fixing this.

can you put this in your `PodFile` and run a `pod update` command?
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'Fixes'
```

If it works well, i will merge this into the next release.

**Comment by juliensagot** [comment]
Works in my projet and in the example project 👍
Thank you very much, that was fast!

**Comment by patchthecode** [comment]
7.1.5 released

**Comment by yuryks** [comment]
Still have this issue. Pod version 7.1.7.  For now removed insets to avoid UI bugs.

**Comment by lsmilek1** [comment]
I can confirm, have the same issue on current version

**Comment by patchthecode** [comment]
Can you tell me the setup you have?
What does your inset look like?

I need know what is your exact setup so that i can re-create the UI bug.

**Comment by lsmilek1** [comment]
Hi,

I am currently struggling with scrollToDate on viewDidLoad. What I am
trying is to have fixed cell height and change calendarView height on
scroll (generating cells till end of row to prevent gap between months for
vertical scroll direction). The issue I have:

1) in viewDidLoad I have to set scroll mode to .none, then scroll and set
scroll mode .stopAtEachSection, otherwise it stops somewhere in the middle
of section
2) I want to have top and bottom insets on section (place for shadow
effect). After scroll in viewDidLoad the insets are ignored - view shows up
scrolled, but I have to scroll manually so it snaps correctly with top
inset. Also "extraAddedOffset" is ignored during the scroll in viewDidLoad.

I am sorry if the code is confusing, I am working today already for 14hrs,
I cant think much straight... Hope it helps!

*import* UIKit

*import* JTAppleCalendar


*class* MonthSceneViewController: UIViewController,
UIGestureRecognizerDelegate {


    *var* month: Int!

    *var* year: Int!

    *var* backLabel: UILabel!

    *var* weekNamesArray: [UILabel] = []

    *var* currentlySelectedDate: Date?

    *let* dayCellSize: CGFloat = 50.0

    *let* topBottomInset: CGFloat = 5.0



    *//variables for detecting swipe back gestures*

    *var* isTouched = *false*

    *var* isPopTouch = *false*



    *let* formatter = DateFormatter()

    *let* deviceCalendar = CalendarUtilities.calendar()



    *@IBOutlet* *weak* *var* navigationBackButton: UIButton!

    *@IBOutlet* *var* backgroundView: UIView!

    *@IBOutlet* *weak* *var* topBarShadowView: UIView!



    *@IBOutlet* *weak* *var* calendarView: JTAppleCalendarView!

    *@IBOutlet* *weak* *var* calendarViewHeight: NSLayoutConstraint!

    *@IBOutlet* *weak* *var* day1Label: UILabel!

    *@IBOutlet* *weak* *var* day2Label: UILabel!

    *@IBOutlet* *weak* *var* day3Label: UILabel!

    *@IBOutlet* *weak* *var* day4Label: UILabel!

    *@IBOutlet* *weak* *var* day5Label: UILabel!

    *@IBOutlet* *weak* *var* day6Label: UILabel!

    *@IBOutlet* *weak* *var* day7Label: UILabel!





    *override* *func* viewDidLoad() {

        *super*.viewDidLoad()

        *self*.navigationController?.interactivePopGestureRecognizer?.
delegate = *self*

        Helpers.setBackgroundGradient(backgroundView: backgroundView)

        topBarShadowView.layer.shadowOpacity = 1.0

        topBarShadowView.layer.shadowColor = UIColor.white.cgColor

        topBarShadowView.layer.shadowRadius = Constants.shadowRadius

        topBarShadowView.layer.shadowOffset = CGSize(width: 0, height: 3)

        calendarView.scrollsToTop = *false* *// prevents scrolling by
taping the status bar*



        setupCalendarView()

        setBackButtonTitle()

        setWeekNames()

    }



    *override* *func* viewWillAppear(*_* animated: Bool) {

        *super*.viewWillAppear(*true*)

        *self*.isPopTouch = *false*

        *self*.navigationController?.setNavigationBarHidden(*true*,
animated: *true*)

        NotificationCenter.default.post(name: .showFloatingBtnNotKey,
object: *nil*)

    }



    *override* *func* viewWillDisappear(*_* animated: Bool) {

        *super*.viewWillDisappear(*true*)

        *if* isTouched { *//for detecting swipe back gestures*

            isPopTouch = *true*

        }

        *if* isPopTouch {

            scrollRootViewToSelectedYear()

        }

    }



*//MARK: Navigaiton functions
----------------------------------------------------*



    *func* gestureRecognizerShouldBegin(*_* gestureRecognizer:
UIGestureRecognizer) -> Bool {

        *if* gestureRecognizer == *self*.navigationController?.
interactivePopGestureRecognizer {

            *self*.isTouched = *true*

        }

        *return* *true*

    }



    *override* *func* touchesEnded(*_* touches: Set<UITouch>, with event:
UIEvent?) {

        *self*.isTouched = *false*

    }



    *@IBAction* *func* backButtonTapped(*_* sender: *Any*) {

        scrollRootViewToSelectedYear()

        *self*.navigationController?.popToRootViewController(animated:
*true*)

    }





    *func* scrollRootViewToSelectedYear() {

        *if* *let* rootVC = *self*.navigationController?.viewControllers[0]
*as*? OurDaysMainViewController {

            rootVC.scrollToYear(year: year)

        }

    }



    *func* popManageTemplatesViewController() {

        performSegue(withIdentifier: "segueManageTemplates", sender: *nil*)

    }





*//MARK: Set views
-------------------------------------------------------------------*



    *func* setBackButtonTitle() {

        *let* monthTitle = Helpers.capitalizingFirstLetter(string: formatter
.standaloneMonthSymbols[month])

        navigationBackButton.setTitle(monthTitle + " " + String(year), for:
.normal)

    }



    *func* setWeekNames() {

        weekNamesArray = [day1Label, day2Label, day3Label, day4Label,
day5Label, day6Label, day7Label]

        *for* i *in* 0...(weekNamesArray.count - 1) {

            *let* weekTitleIndex = (i + (deviceCalendar.firstWeekday - 1))
% 7

            *let* weekTitle = Helpers.capitalizingFirstLetter(string:
formatter.shortStandaloneWeekdaySymbols[weekTitleIndex])

            weekNamesArray[i].text = weekTitle

        }

    }





}


*extension* MonthSceneViewController: JTAppleCalendarViewDelegate {



    *func* calendar(*_* calendar: JTAppleCalendarView, cellForItemAt date:
Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {

        *let* cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier:
"monthCell", for: indexPath) *as*! MonthSceneCollectionViewCell

        cell.dateLabel.text = cellState.text

        handleConfiguration(cell: cell, cellState: cellState)

        *return* cell

    }



    *func* calendar(*_* calendar: JTAppleCalendarView, willDisplay cell:
JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath:
IndexPath) {

        *//any visual issues to reload here?*

    }



    *func* calendar(*_* calendar: JTAppleCalendarView, didSelectDate date:
Date, cell: JTAppleCell?, cellState: CellState) {

        *guard* *let* cell = cell *as*? MonthSceneCollectionViewCell *else*
{ *return* }

        handleConfiguration(cell: cell, cellState: cellState)

    }



    *func* calendar(*_* calendar: JTAppleCalendarView, didDeselectDate
date: Date, cell: JTAppleCell?, cellState: CellState) {

        *guard* *let* cell = cell *as*? MonthSceneCollectionViewCell *else*
{ *return* }

        handleConfiguration(cell: cell, cellState: cellState)

    }



    *func* calendar(*_* calendar: JTAppleCalendarView,
didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {

        *guard* *let* date = visibleDates.monthDates.first?.date *else* {
*return* }

        month = deviceCalendar.component(.month, from: date) - 1

        year = deviceCalendar.component(.year, from: date)

        setBackButtonTitle()

        *let* status = calendarView.cellStatus(for: date)

        *let* monthRowCount = status?.dateSection().rowCount

        view.layoutIfNeeded()

        *if* calendarViewHeight.constant != ((CGFloat(monthRowCount!) *
dayCellSize) + (topBottomInset * 2)) {

            *self*.calendarViewHeight.constant = ((CGFloat(monthRowCount!)
* *self*.dayCellSize) + (*self*.topBottomInset * 2))

        }

*//        UIView.animate(withDuration: 0.2, animations: { () -> Void in*

*//            self.view.layoutIfNeeded()*

*//        })*

    }







}


*extension* MonthSceneViewController: JTAppleCalendarViewDataSource {



    *func* configureCalendar(*_* calendar: JTAppleCalendarView) ->
ConfigurationParameters {

        formatter.dateFormat = "yyyy MM dd"

        formatter.timeZone = Calendar.current.timeZone

        formatter.locale = Calendar.current.locale

        *let* startDate = "\((year ?? CalendarUtilities.currentYear()) - 2)
01 01"

        *let* endDate = "\((year ?? CalendarUtilities.currentYear()) + 3)
12 31"

        *let* formatedStartDate = formatter.date(from: startDate)!

        *let* formatedEndDate = formatter.date(from: endDate)!

        *let* parameters = ConfigurationParameters(startDate:
formatedStartDate, endDate: formatedEndDate, generateInDates: .forAllMonths,
generateOutDates: .tillEndOfRow, firstDayOfWeek: DaysOfWeek(rawValue:
deviceCalendar.firstWeekday) ?? .monday)

        *return* parameters

    }



    *func* setupCalendarView() {

        calendarView.minimumLineSpacing = 0

        calendarView.minimumInteritemSpacing = 0

        calendarView.cellSize = dayCellSize

        calendarView.sectionInset = UIEdgeInsets(top: topBottomInset, left:
0, bottom: topBottomInset, right: 0)

        *let* date = deviceCalendar.date(from: DateComponents(year: year,
month: month + 1, day: 1))

        calendarView.scrollingMode = .none

        calendarView.scrollToDate(date ?? Date(), animateScroll: *false*,
extraAddedOffset: topBottomInset) { () *in*

            *self*.calendarView.scrollingMode = .stopAtEachSection

            *let* componentsOfToday = *self*.deviceCalendar.dateComponents
([.month, .year], from: Date())

            *if* ((componentsOfToday.month ?? 1) - 1) == *self*.month &&
componentsOfToday.year == *self*.year {

                *self*.calendarView.selectDates([Date()])

            }

        }

*//        let componentsOfToday = deviceCalendar.dateComponents([.month,
.year], from: Date())*

*//        if ((componentsOfToday.month ?? 1) - 1) == month &&
componentsOfToday.year == year {*

*//            calendarView.selectDates([Date()])*

*//        }*

    }



    *func* setCalendarViewHeight(animated: Bool) {

        *let* visibleDates = calendarView.visibleDates()

        *guard* *let* date = visibleDates.monthDates.first?.date *else* {
*return* }

        *let* status = calendarView.cellStatus(for: date)

        *let* monthRowCount = status?.dateSection().rowCount

        view.layoutIfNeeded()

        *if* calendarViewHeight.constant != ((CGFloat(monthRowCount!) *
dayCellSize) + (topBottomInset * 2)) {

            *self*.calendarViewHeight.constant = ((CGFloat(monthRowCount!)
* *self*.dayCellSize) + (*self*.topBottomInset * 2))

        }

        *if* animated {

            UIView.animate(withDuration: 0.2, animations: { () -> Void *in*

                *self*.view.layoutIfNeeded()

            })

        }

    }



}



*//MARK: JTAppleCalendar funtions
----------------------------------------------------------*


*extension* MonthSceneViewController {









    *func* handleConfiguration(cell: JTAppleCell?, cellState: CellState) {

        *guard* *let* cell = cell *as*? MonthSceneCollectionViewCell *else*
{ *return* }

        cell.selectedView.layer.cornerRadius = cell.selectedView.frame.size.
width / 2

        handleCellVisibility(cell: cell, cellState: cellState)

        handleCellSelection(cell: cell, cellState: cellState)

        handleCalendarWeekNumber(cell: cell, cellState: cellState)

    }



    *func* handleCellVisibility(cell: MonthSceneCollectionViewCell,
cellState: CellState) {

        cell.isHidden = cellState.dateBelongsTo == .thisMonth ? *false* :
*true*

    }



    *func* handleCellSelection(cell: MonthSceneCollectionViewCell,
cellState: CellState) {

        cell.selectedView.isHidden = !cellState.isSelected

        *if* cellState.isSelected {

*//            cell.selectedView.isHidden = false*

*//            cell.selectedView.backgroundColor = UIColor(named:
"MainColor")*

            cell.dateLabel.textColor = .white

            cell.dateLabel.font = .systemFont(ofSize: 17, weight: .regular)

        } *else* {

            *if* deviceCalendar.isDateInToday(cellState.date) {

*//                cell.selectedView.isHidden = false*

*//                cell.selectedView.backgroundColor = UIColor(named:
"SeparatorLine")*

                cell.dateLabel.textColor = UIColor(named: "MainColor")

                cell.dateLabel.font = .systemFont(ofSize: 17, weight: .bold)

            } *else* {

*//                cell.selectedView.isHidden = true*

                cell.dateLabel.textColor = .black

                cell.dateLabel.font = .systemFont(ofSize: 17, weight: .
regular)

            }

        }

    }



    *func* handleCalendarWeekNumber(cell: MonthSceneCollectionViewCell,
cellState: CellState) {

        *let* cellWeek = CalendarUtilities.calendarWeekOfDate(date:
cellState.date)

        *let* currentWeek = deviceCalendar.component(.weekOfYear, from: Date
())

        *if* cellState.day == DaysOfWeek(rawValue: deviceCalendar.
firstWeekday) ?? .monday {

            cell.weekNumberLabel.isHidden = *false*

            cell.weekNumberLabel.text = String(cellWeek)

            *if* cellWeek == currentWeek {

                cell.weekNumberLabel.textColor = UIColor(named: "MainColor")

                cell.weekNumberLabel.font = .systemFont(ofSize: 12, weight:
.bold)

            } *else* {

                cell.weekNumberLabel.textColor = .lightGray

                cell.weekNumberLabel.font = .systemFont(ofSize: 12, weight:
.regular)

            }

        } *else* {

            cell.weekNumberLabel.isHidden = *true*

            cell.weekNumberLabel.text = "cw"

        }

*//        cell.separatorLine.backgroundColor = cellWeek == currentWeek ?
UIColor(named: "MainColor") : UIColor(named: "SeparatorLine")*

    }



}

pá 8. 3. 2019 v 20:05 odesílatel JTAppleCalendar <notifications@github.com>
napsal:

**Comment by patchthecode** [comment]
@lsmilek1 
ok... can you provide a sample app with your issue? Just zip the project and drag it into the chat box.
I cannot determine what your problem is from a long code post in chat like this.

**Comment by lsmilek1** [comment]
`class MonthSceneViewController: UIViewController,UIGestureRecognizerDelegate {

    var month: Int!
    var year: Int!
    var backLabel: UILabel!
    var weekNamesArray: [UILabel] = []
    var currentlySelectedDate: Date?
    let dayCellSize: CGFloat = 52.0
    let topBottomInset: CGFloat = 5.0
    
    //variables for detecting swipe back gestures
    var isTouched = false
    var isPopTouch = false
    
    let formatter = DateFormatter()
    let deviceCalendar = CalendarUtilities.calendar()
    
    @IBOutlet weak var navigationBackButton: UIButton!
    @IBOutlet var backgroundView: UIView!
    @IBOutlet weak var topBarShadowView: UIView!
    
    @IBOutlet weak var calendarView: JTAppleCalendarView!
    @IBOutlet weak var calendarViewHeight: NSLayoutConstraint!
    @IBOutlet weak var day1Label: UILabel!
    @IBOutlet weak var day2Label: UILabel!
    @IBOutlet weak var day3Label: UILabel!
    @IBOutlet weak var day4Label: UILabel!
    @IBOutlet weak var day5Label: UILabel!
    @IBOutlet weak var day6Label: UILabel!
    @IBOutlet weak var day7Label: UILabel!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.interactivePopGestureRecognizer?.delegate = self
        Helpers.setBackgroundGradient(backgroundView: backgroundView)
        topBarShadowView.layer.shadowOpacity = 1.0
        topBarShadowView.layer.shadowColor = UIColor.white.cgColor
        topBarShadowView.layer.shadowRadius = Constants.shadowRadius
        topBarShadowView.layer.shadowOffset = CGSize(width: 0, height: 3)
        calendarView.scrollsToTop = false // prevents scrolling by taping the status bar
        
        setupCalendarView()
        setBackButtonTitle()
        setWeekNames()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        self.isPopTouch = false
        self.navigationController?.setNavigationBarHidden(true, animated: true)
        NotificationCenter.default.post(name: .showFloatingBtnNotKey, object: nil)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(true)
        if isTouched { //for detecting swipe back gestures
            isPopTouch = true
        }
        if isPopTouch {
            scrollRootViewToSelectedYear()
        }
    }
    
//MARK: Navigaiton functions ----------------------------------------------------
    
    func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        if gestureRecognizer == self.navigationController?.interactivePopGestureRecognizer {
            self.isTouched = true
        }
        return true
    }
    
    override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
        self.isTouched = false
    }
    
    @IBAction func backButtonTapped(_ sender: Any) {
        scrollRootViewToSelectedYear()
        self.navigationController?.popToRootViewController(animated: true)
    }
    
    
    func scrollRootViewToSelectedYear() {
        if let rootVC = self.navigationController?.viewControllers[0] as? OurDaysMainViewController {
            rootVC.scrollToYear(year: year)
        }
    }
    
    func popManageTemplatesViewController() {
        performSegue(withIdentifier: "segueManageTemplates", sender: nil)
    }
    
    
//MARK: Set views -------------------------------------------------------------------
    
    func setBackButtonTitle() {
        let monthTitle = Helpers.capitalizingFirstLetter(string: formatter.standaloneMonthSymbols[month])
        navigationBackButton.setTitle(monthTitle + " " + String(year), for: .normal)
    }
    
    func setWeekNames() {
        weekNamesArray = [day1Label, day2Label, day3Label, day4Label, day5Label, day6Label, day7Label]
        for i in 0...(weekNamesArray.count - 1) {
            let weekTitleIndex = (i + (deviceCalendar.firstWeekday - 1)) % 7
            let weekTitle = Helpers.capitalizingFirstLetter(string: formatter.shortStandaloneWeekdaySymbols[weekTitleIndex])
            weekNamesArray[i].text = weekTitle
        }
    }
    
   
}

extension MonthSceneViewController: JTAppleCalendarViewDelegate {
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = 	calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "monthCell", for: indexPath) as! MonthSceneCollectionViewCell
        cell.dateLabel.text = cellState.text
        handleConfiguration(cell: cell, cellState: cellState)
        return cell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        //any visual issues to reload here?
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        guard let cell = cell as? MonthSceneCollectionViewCell else { return }
        handleConfiguration(cell: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        guard let cell = cell as? MonthSceneCollectionViewCell else { return }
        handleConfiguration(cell: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        guard let date = visibleDates.monthDates.first?.date else { return }
        month = deviceCalendar.component(.month, from: date) - 1
        year = deviceCalendar.component(.year, from: date)
        setBackButtonTitle()
        let status = calendarView.cellStatus(for: date)
        let monthRowCount = status?.dateSection().rowCount
        view.layoutIfNeeded()
        if calendarViewHeight.constant != ((CGFloat(monthRowCount!) * dayCellSize) + (topBottomInset * 2)) {
            self.calendarViewHeight.constant = ((CGFloat(monthRowCount!) * self.dayCellSize) + (self.topBottomInset * 2))
        }
//        UIView.animate(withDuration: 0.2, animations: { () -> Void in
//            self.view.layoutIfNeeded()
//        })
    }
    
    
    
}

extension MonthSceneViewController: JTAppleCalendarViewDataSource {
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        let startDate = "\((year ?? CalendarUtilities.currentYear()) - 2) 01 01"
        let endDate = "\((year ?? CalendarUtilities.currentYear()) + 3) 12 31"
        let formatedStartDate = formatter.date(from: startDate)!
        let formatedEndDate = formatter.date(from: endDate)!
        let parameters = ConfigurationParameters(startDate: formatedStartDate, endDate: formatedEndDate, generateInDates: .forAllMonths, generateOutDates: .tillEndOfRow, firstDayOfWeek: DaysOfWeek(rawValue: deviceCalendar.firstWeekday) ?? .monday)
        return parameters
    }
    
    func setupCalendarView() {
        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
        calendarView.cellSize = dayCellSize
        calendarView.sectionInset = UIEdgeInsets(top: topBottomInset, left: 0, bottom: topBottomInset, right: 0)
        let date = deviceCalendar.date(from: DateComponents(year: year, month: month + 1, day: 1))
        calendarView.scrollingMode = .none
        calendarView.scrollToDate(date ?? Date(), animateScroll: false, extraAddedOffset: topBottomInset) { () in
            self.calendarView.scrollingMode = .stopAtEachSection
            let componentsOfToday = self.deviceCalendar.dateComponents([.month, .year], from: Date())
            if ((componentsOfToday.month ?? 1) - 1) == self.month && componentsOfToday.year == self.year {
                self.calendarView.selectDates([Date()])
            }
        }
//        let componentsOfToday = deviceCalendar.dateComponents([.month, .year], from: Date())
//        if ((componentsOfToday.month ?? 1) - 1) == month && componentsOfToday.year == year {
//            calendarView.selectDates([Date()])
//        }
    }
    
    func setCalendarViewHeight(animated: Bool) {
        let visibleDates = calendarView.visibleDates()
        guard let date = visibleDates.monthDates.first?.date else { return }
        let status = calendarView.cellStatus(for: date)
        let monthRowCount = status?.dateSection().rowCount
        view.layoutIfNeeded()
        if calendarViewHeight.constant != ((CGFloat(monthRowCount!) * dayCellSize) + (topBottomInset * 2)) {
            self.calendarViewHeight.constant = ((CGFloat(monthRowCount!) * self.dayCellSize) + (self.topBottomInset * 2))
        }
        if animated {
            UIView.animate(withDuration: 0.2, animations: { () -> Void in
                self.view.layoutIfNeeded()
            })
        }
    }
    
}


//MARK: JTAppleCalendar funtions ----------------------------------------------------------

extension MonthSceneViewController {
    
    
    
    
    func handleConfiguration(cell: JTAppleCell?, cellState: CellState) {
        guard let cell = cell as? MonthSceneCollectionViewCell else { return }
        cell.selectedView.layer.cornerRadius = cell.selectedView.frame.size.width / 2
        handleCellVisibility(cell: cell, cellState: cellState)
        handleCellSelection(cell: cell, cellState: cellState)
        handleCalendarWeekNumber(cell: cell, cellState: cellState)
    }
    
    func handleCellVisibility(cell: MonthSceneCollectionViewCell, cellState: CellState) {
        cell.isHidden = cellState.dateBelongsTo == .thisMonth ? false : true
    }
    
    func handleCellSelection(cell: MonthSceneCollectionViewCell, cellState: CellState) {
        cell.selectedView.isHidden = !cellState.isSelected
        if cellState.isSelected {
//            cell.selectedView.isHidden = false
//            cell.selectedView.backgroundColor = UIColor(named: "MainColor")
            cell.dateLabel.textColor = .white
            cell.dateLabel.font = .systemFont(ofSize: 17, weight: .regular)
        } else {
            if deviceCalendar.isDateInToday(cellState.date) {
//                cell.selectedView.isHidden = false
//                cell.selectedView.backgroundColor = UIColor(named: "SeparatorLine")
                cell.dateLabel.textColor = UIColor(named: "MainColor")
                cell.dateLabel.font = .systemFont(ofSize: 17, weight: .bold)
            } else {
//                cell.selectedView.isHidden = true
                cell.dateLabel.textColor = .black
                cell.dateLabel.font = .systemFont(ofSize: 17, weight: .regular)
            }
        }
    }
    
    func handleCalendarWeekNumber(cell: MonthSceneCollectionViewCell, cellState: CellState) {
        let cellWeek = CalendarUtilities.calendarWeekOfDate(date: cellState.date)
        let currentWeek = deviceCalendar.component(.weekOfYear, from: Date())
        if cellState.day == DaysOfWeek(rawValue: deviceCalendar.firstWeekday) ?? .monday {
            cell.weekNumberLabel.isHidden = false
            cell.weekNumberLabel.text = String(cellWeek)
            if cellWeek == currentWeek {
                cell.weekNumberLabel.textColor = UIColor(named: "MainColor")
                cell.weekNumberLabel.font = .systemFont(ofSize: 12, weight: .bold)
            } else {
                cell.weekNumberLabel.textColor = .lightGray
                cell.weekNumberLabel.font = .systemFont(ofSize: 12, weight: .regular)
            }
        } else {
            cell.weekNumberLabel.isHidden = true
            cell.weekNumberLabel.text = "cw"
        }
//        cell.separatorLine.backgroundColor = cellWeek == currentWeek ? UIColor(named: "MainColor") : UIColor(named: "SeparatorLine")
    }
    
}
`

**Comment by patchthecode** [comment]
can you test and let me know if the fixed i pushed to master branch worked?
[Instrunctions here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions)

**Comment by patchthecode** [comment]
@lsmilek1 
if it is fixed, i will close this issue

**Comment by lsmilek1** [comment]
Trying it in the main app and keeping scroll mode first .none and then switching back I got error here:

UserInteracionsFunctions.swift, public func scrollToDate, line 524:

`guard let point = targetPointForItemAt(indexPath: sectionIndexPath) else {
            assert(false, "Could not determine CGPoint. This is an error. contact developer on github. In production, there will not be a crash, but scrolling will not occur")
            return
        }`

keeping scroll mode .stopAtEachSection cause no error, but it still scrolls misaligned. I will try later today on the sample app or play with "extraAddedOffset" if it helps. Thank you!

**Comment by yuryks** [comment]
@patchthecode 
Not fixed for scrollDirection`.vertical` and `scrollToHeaderForDate`.
Project example: [JTAppleCalendarInsetsErrorDemo.zip](https://github.com/patchthecode/JTAppleCalendar/files/2952345/JTAppleCalendarInsetsErrorDemo.zip)

**Comment by lsmilek1** [comment]
So... Following is done in simulator... I updated the pod according to your instructions in the sample app I shared above. Here it's how it looks when scrolling mode is .stopAtEachSection and I scroll to 11th August 2019 while startDate of the calendar is 1st January 2017:
![Snímek obrazovky 2019-03-11 v 15 58 22](https://user-images.githubusercontent.com/41491201/54133701-d54be180-4416-11e9-89d9-4c22e8020b01.png)
When I try to scroll a little, it snaps all good with insets:
![Snímek obrazovky 2019-03-11 v 16 01 07](https://user-images.githubusercontent.com/41491201/54133775-f3b1dd00-4416-11e9-8f8e-81b6ec2b981d.png)
With scroll mode .none and switching back in completion handler to .stopAtEachSection, the august appears better, but still ignoring top inset. And after a little of manual scroll is the position again all good as above.
![Snímek obrazovky 2019-03-11 v 16 02 38](https://user-images.githubusercontent.com/41491201/54133940-4e4b3900-4417-11e9-84e1-d6ab63809a50.png)

Interesting is, that I get no crash. But If I try the same in my App (simulator and device) I get a crash while loading if I use .none mode.
![Snímek obrazovky 2019-03-11 v 16 17 45](https://user-images.githubusercontent.com/41491201/54135175-9ff4c300-4419-11e9-9679-7a08cd6188da.png)

If I use .stopAtEachSection I get no crash, but it looks the same like in the sample app
![Snímek obrazovky 2019-03-11 v 16 15 15](https://user-images.githubusercontent.com/41491201/54135280-cca8da80-4419-11e9-870c-0c9ce9baa883.png)
Scrolling to March in viewDidLoad even shows February dates as there is probably a little of previous month visible
![Snímek obrazovky 2019-03-11 v 16 25 12](https://user-images.githubusercontent.com/41491201/54135535-45a83200-441a-11e9-84bc-0217e4ed43bd.png)

If you want and it would be any help, I can share my screen to show you the behaviour and the code. Thank you!

**Comment by patchthecode** [comment]
ok just woke up.
Checking this out again

**Comment by patchthecode** [comment]
@lsmilek1 

Ok something important. Some of the errors you are seeing may be because of cached build. Also, i made a small change to account for the inset on scroll without header. Therefore please do the following and let me know the results.

1. make sure you have master branch in the Podfile again, then do the following command again because i made a small update.
```
pod update
```
2. After doing this, in your Xcode project, **make sure** you do a `CMD + SHIFT + K` to clean your project. If you do not do this it will use old build code. I scratch my head for about 20 mins before i realized my fix was not being used in your sample project until i cleaned.

Notes:
1. Setting scrollmode to none should no longer behave badly. (code here was incomplete when i made the fix for the other scroll mode.)
2. Setting the scrollMode to = None, will behave like you showed above. Meaning, it will ignore insets. A scroll mode of none does not respect anything. It is free scrolling.

Let me know the results.

**Comment by patchthecode** [comment]
@yuryks 
Checking into your issue now

**Comment by patchthecode** [comment]
@yuryks 
i think your issue is resolved with the latest fix?
I downloaded your sample project and i didnt see any UI issues.

**Comment by yuryks** [comment]
@patchthecode 

![insets_ios12 1_simulator](https://user-images.githubusercontent.com/39466996/54178242-d1af6d80-449d-11e9-900b-d82c82acd2b6.gif)

 I am still facing insets error (pay attention to left inset before and after scroll).  Maybe it is simulator only issue, will check on device later today. (MacOS 10.13.6, Xcode 10.1 (10B61), iOS 12.1 Simulator)
 
 Here is my updated sample project (i have changed background colors for cell and header).
[JTAppleCalendarInsetsErrorDemo1.zip](https://github.com/patchthecode/JTAppleCalendar/files/2955352/JTAppleCalendarInsetsErrorDemo1.zip)

**Comment by patchthecode** [comment]
@yuryks 
ok i see it now.
Checking this out.

**Comment by patchthecode** [comment]
@yuryks 
Ok, please do
1. pod update
2. Xcode Clean (to get rid of cached build)
3. Let me know if bug is still there

**Comment by yuryks** [comment]
@patchthecode it works now as expected. Thanks.

**Comment by lsmilek1** [comment]
I am sending my deepest apologies and a symbolic contribution on https://opencollective.com/JTAppleCalendar for my inexperience omission of cleaning the build, I am still a beginner! 

Scrolling mode .stopAtEachSection with a bit of "extraAddedOfsett" works perfect now. Also no flashing of pervious months, no crash. All good! 

Thank you very much for your prompt support!

**Comment by patchthecode** [comment]
awesome.
glad it worked.
continue using master branch until i release version 7.1.8 shortly
